### PR TITLE
Improve logging

### PR DESCRIPTION
**Pull request by rudigiesler**

### CODE REVIEW

**Comment by rudigiesler** [comment]
@hodgestar Just something I noticed while testing with Junebug in the previous PR. Ready for review.

**Comment by hodgestar** [comment]
I think it might be cleaner to delete the `self.log` method and do `self.log = vumi_transport.log` in the constructor? (and we could also remove the import of `log` from `vumi`).

**Comment by rudigiesler** [comment]
@hodgestar I decided to keep the existing logging function rather. I feel like it's cleaner than having to manually put the channel ID everywhere. Ready for review now

**Comment by hodgestar** [comment]
:+1:

**Pull request merged**
